### ISSUE TITLE
Run composer dump-autoload after generation

### ISSUE THREAD

**Issue by RomainLanz** [laracasts/Laravel-5-Generators-Extended#10]
Hi everyone,

What do you think about calling `composer dump-autoload`after generating some classes? Like a seeder.

**Comment by zoransa** [comment]
Hey!
Yes this command should do ```composer dump-autoload -o``` by default and have switch no-dump-autoload to turn it off

**Comment by philsown** [comment]
(y)

**Comment by hendrikusR** [comment]
![capture_001_01102015_151936](https://cloud.githubusercontent.com/assets/10723002/10215963/f33d733a-684f-11e5-8665-2d6d881e3592.jpg)
i have problem with composer dump-autoload, how i solve?

**Comment by Shentia** [comment]
i just use composer dump-autoload -o and work fine.
**Generating optimized autoload files**

**Comment by Michal-sk** [comment]
This is an older issue, but i would agree that if there would be an option to auto run the optimized dump-autoload after update or install, i would enable it.

**Comment by tabacitu** [comment]
Hi everyone - sorry you didn't get an answer for so long. It looks to me like now in 2020 this is no longer an issue - I see ```MakeMigrationCommand.php``` already includes a dump autoload. Let me know if I'm mistaken, and we'll reopen the issue.

Cheers!
