### ISSUE TITLE
how add another parameter for example: decimal('amount', 5, 2)

### ISSUE THREAD

**Issue by ybagheri** [laracasts/Laravel-5-Generators-Extended#101]
how add another parameters like below:
$table->decimal('amount', 5, 2);  
$table->double('column', 15, 8);  
$table->enum('choices', ['foo', 'bar']);
$table->char('name', 4);

how add 5 and 2 in decimal ?

**Comment by Yolcar** [comment]
To add the decimals placed in parentheses. example
amount:decimal(5,2)
Generates the following:
$table->decimal('amount', 5, 2);

**Comment by tabacitu** [comment]
Thank you for asking @ybagheri and answering @Yolcar 😄 

Closing the issue since it seems a solution is already available.
Cheers!
