### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by imanghafoori1** [laracasts/Laravel-5-Generators-Extended#104]
Recently I encountered a tool in node.js world called "LoopBack" which aid creating restful APIs by generating javascript code.
Basically, It provides a nice interactive shell.

Visit loopback.io
TutsPlus - Generate REST APIs With LoopBack

It is nice to have such a thing in laravel.

**Comment by tabacitu** [comment]
Hi @imanghafoori1 - loopback looks nice, but I'm afraid Jeffrey no longer has the time to maintain this package. He's given me write access, but my goal is right now only to bring it up-to-date and close issues and PRs, not provide any more features. I have [12+ repositories myself in Backpack](https://github.com/laravel-backpack/) that take priority. So I'm afraid if you really want this feature, the only way to get it would be to fork this repository and add it.

Cheers!
