### ISSUE TITLE
There are no commands defined in the "make:migration" namespace

### ISSUE THREAD

**Issue by mexists** [laracasts/Laravel-5-Generators-Extended#106]
I add the generators using `composer require laracasts/generators --dev`

and added this to `app/Providers/AppServiceProvider.php`
![image](https://cloud.githubusercontent.com/assets/12674214/17082291/606e12d6-51aa-11e6-87e7-975b1efa98d0.png)

then when I tried to make a schema using command `php artisan make:migration:schema`
![image](https://cloud.githubusercontent.com/assets/12674214/17082267/c7a20e2c-51a9-11e6-8594-63e8da2cf107.png)

did I missed anything?

**Laravel 5.2.41**
**Windows**
**ngnix**
**PHP 5.6**

**Comment by mexists** [comment]
#108 seems this bug is new

**Comment by ssirjann** [comment]
This is probably because the if condition inside the register function of AppServiceProvider.php is failing. 
Maybe your installation is not local. Check for a .env file in root directory of your Laravel installation. 
If this still doesn't work, then for now, you can remove the if, **which is not recommended.**

**Comment by BartHuis** [comment]
I get it too when using after adding the package with composer:
```
$ artisan make:migration:pivot promotions multimedia_objects


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "make:migration" namespace.
  Did you mean this?
      make

```

**Comment by BartHuis** [comment]
do you know what's happening here @JeffreyWay ?

**Comment by BartHuis** [comment]
whoops, forgot step 2, now it works:
```
Step 2: Add the Service Provider

You'll only want to use these generators for local development, so you don't want to update the production providers array in config/app.php. Instead, add the provider in app/Providers/AppServiceProvider.php, like so:

public function register()
{
    if ($this->app->environment() == 'local') {
        $this->app->register('Laracasts\Generators\GeneratorsServiceProvider');
    }
}
```

**Comment by iyadh** [comment]
I've solved this issue by creating a .env in my project root with this setting:
`APP_ENV=local`
Then the command worked as expected.

**Comment by TCB13** [comment]
I'm running into this in Lumen. Lumen (5.3.3) (Laravel Components 5.3.*).

The solutions above doesn't seem to fix the issue:

**.env**:
```APP_ENV=local```

`AppServiceProvider.php`:
`````
 public function register()
    {
        
        if ($this->app->environment() == "local") {
        	$this->app->register('Laracasts\Generators\GeneratorsServiceProvider');
    	}

    }
````

What am I missing? Thank you.
