### ISSUE TITLE
drop foreign keys

### ISSUE THREAD

**Issue by sevmardi** [laracasts/Laravel-5-Generators-Extended#111]
Hi! 

I was wondering if it is possible to drop foreign keys from a particular table? 
I tried different things using this tool, but couldn't get it working. I also checked the other issues.  

Any ideas?

**Comment by sevmardi** [comment]
```
$table->dropForeign(['supplier_id']);
$table->dropColumn('supplier_id');
```
Did the trick. Any other methods I should know about?

**Comment by Jeloo** [comment]
@sevmardi i think you also should drop index like
`$table->dropIndex('supplier_id_foreign')`
(the name of index is just an example. It is usually the same as foreign key name)
