### ISSUE TITLE
How to disable Model Creation? 

### ISSUE THREAD

**Issue by santoshachari** [laracasts/Laravel-5-Generators-Extended#112]
Hey there! 

Thanks again for the plugin. 

I see model generation is on by default. I've tried `--model=false`, and it doesn't work, how can I disable?

TIA

**Comment by anchepiece** [comment]
What was your complete command? Did you have --model=false before the name?

**Comment by santoshachari** [comment]
I have tried it both ways, it doesn't seem to work. 
<img width="943" alt="screen shot 2016-10-20 at 11 16 53 am" src="https://cloud.githubusercontent.com/assets/4654290/19553967/c2abd676-96b6-11e6-87fc-a22334ee95b6.png">

**Comment by seanmangar** [comment]
Looking at the code, seems that the option is a string "false". In PHP non empty strings always evaluate to true. Submitting a PR to fix this.

` protected function makeModel()
    {
        $modelPath = $this->getModelPath($this->getModelName());

        if ($this->option('model') && !$this->files->exists($modelPath)) {
            $this->call('make:model', [
                'name' => $this->getModelName()
            ]);
        }
    }`

**Comment by tucq88** [comment]
@JeffreyWay Could you please consider merge PR for fixing this issue ?

**Comment by anchepiece** [comment]
Also take a look at issue #96

**Comment by doctorthompson** [comment]
Passing `--model=0` works.

**Comment by tabacitu** [comment]
Closing this as ```--model=0``` works fine. In v2 we're planning on creating NO MODEL by default. Feedback here please https://github.com/laracasts/Laravel-5-Generators-Extended/pull/170
