### ISSUE TITLE
Foreign keys

### ISSUE THREAD

**Issue by DarkponyLtd** [laracasts/Laravel-5-Generators-Extended#12]
when using 

"user_id:integer:foreign"

the unsigned flag needs to be added to the user_id field before the foreign_key column

e.g. this needs to create

$table->integer('user_id')**->unsigned()**;
$table->foreign('user_id')->references('id')->on('users');

instead of 

$table->integer('user_id');
$table->foreign('user_id')->references('id')->on('users');

**Comment by laracasts** [comment]
```
user_id:integer:unsigned:foreign
```

**Comment by DarkponyLtd** [comment]
Thanks Jeff, this works but still, documentation needs updating. It is misleading.

https://github.com/laracasts/Laravel-5-Generators-Extended#foreign-constraints

anyhow, since foreign keys mainly (if not always) match primary keys, this could have been pre-setted without the need of the :unsigned flag.
