### ISSUE TITLE
Laravel 5.4 update seems stable. Could you please tag it? 

### ISSUE THREAD

**Issue by tabacitu** [laracasts/Laravel-5-Generators-Extended#124]
Hi @JeffreyWay ,

I've been using the L5.4 updates (the 5 untagged commits) for a few days now and found zero issues, both on L5.3 and L5.4. The changes are minor and backwards-compatible. I think it's stable and ready for a release. 

**When do you think you can release the 1.1.4 tag?**

Thanks a lot for all the work you're doing. Cheers!

**Comment by vpratfr** [comment]
Same question here. Thanks too.

**Comment by villeneuve-michael** [comment]
Meanwhile I fixed it using : 

        "laracasts/generators": "master@dev",

To drop down to minimum-stability for the package.

**Comment by cohan** [comment]
Using master@dev as mentioned doesn't seem to play nicely when creating pivot tables. Resulting migration file doesn't have a class name

`class App\ extends Migration`

Fresh install of Laravel 5.4 and master@dev laracasts/generators

**Comment by mmjjb** [comment]
1. Install bug
2. Bug with creating pivot tables

Going very fluently....

**Comment by qeifar** [comment]
@mmjjb  what did u mean by install bug?

**Comment by mmjjb** [comment]
@qeifar Bad explained from me. I was referring to the fact that we have to use an minimum stability package in order to make it work (install issues) and that when we finally have it working, that we have an problem with the name creation. 

Why is this issue not being resolved? This issue is regarding 5.4 and we are slowly already moving to 5.5.
Is this project to be considered dead?

**Comment by tabacitu** [comment]
Hi guys,

Jeffrey has been kind enough to give me write access to the repository, so:
- I've just tagged the release, you can now use it after a ```composer update```;
- I'll do my best from now on to keep this reasonably up-to-date, but please keep in mind I have [12 other repositories in Backpack](https://github.com/Laravel-Backpack) that are my priority, so I can't dedicate a lot of time to this; any help is truly appreciated;

Cheers!
