### ISSUE TITLE
make seed creates folder App in the database/seeds folder?

### ISSUE THREAD

**Issue by nousename** [laracasts/Laravel-5-Generators-Extended#129]
Is this meant to happen?
and puts the created seeds into the App folder

**Comment by bogdankharchenko** [comment]
No it should not, this is addressed in PR, https://github.com/laracasts/Laravel-5-Generators-Extended/pull/154

**Comment by MrHeliox** [comment]
Has this not been fixed ?

**Comment by amberlampsio** [comment]
> Has this not been fixed ?

It was merged but release was not cut, just switch it to master-dev version in composer.

**Comment by MrHeliox** [comment]
> > Has this not been fixed ?
> 
> It was merged but release was not cut, just switch it to master-dev version in composer.

How can I do this ?

**Comment by amberlampsio** [comment]
> > > Has this not been fixed ?
> > 
> > 
> > It was merged but release was not cut, just switch it to master-dev version in composer.
> 
> How can I do this ?

in require-dev section of composer.json, 

put 
```
        "laracasts/generators": "dev-master"
```

**Comment by tabacitu** [comment]
Looks like this has been fixed in the meantime, so I'm going to close the issue. Thanks everyone for pitching in. Cheers!
