### ISSUE TITLE
CustomModel for Pivot Generator

### ISSUE THREAD

**Issue by cs-abdulwahab** [laracasts/Laravel-5-Generators-Extended#130]
In Laravel 5.4   , Custom Model can be used as Intermediate Pivot Table
it would be handy if  create model option be given 
when running command php artisan make:migration:pivot table1 table2  -model=CustomModel

**Comment by tabacitu** [comment]
Thank you @cs-abdulwahab but I'm afraid this is very rarely used, especially when using Generators. Let me know if you'd like to contribute with a PR on this - we might consider it then. If so, there's no better time like the present, we're working on launching v2 https://github.com/laracasts/Laravel-5-Generators-Extended/pull/170 and it would be great to have this inside it too.

Cheers!
