### ISSUE TITLE
api not working on my app laravel 5.4

### ISSUE THREAD

**Issue by enasellithy** [laracasts/Laravel-5-Generators-Extended#131]
$api = app('Dingo\Api\Routing\Router');
$api->version('v1',function($api){
	$api->get('hello',function(){
		return "Hello";
	});
});
in api file
'domain' => env('API_DOMAIN', 'http://127.0.0.1:8000/api/hello'),
but show to me in browse
![capture](https://user-images.githubusercontent.com/17440978/26999657-6a69141a-4d9f-11e7-8dfd-660a4bbf6ad3.PNG)

**Comment by tabacitu** [comment]
Hi @enasellithy - sorry but I'm going to have to close this. It doesn't look like a generators error at all. Cheers!
