### ISSUE TITLE
Problem installing 'composer require laracasts/generators --dev' in 5.5

### ISSUE THREAD

**Issue by bocha95** [laracasts/Laravel-5-Generators-Extended#139]
Using version ^1.1 for laracasts/generators
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing laracasts/generators (1.1.3): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Fatal error:  Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found in /Users/bochita/Documents/Laravel-Projects/PaymentBackPack/vendor/laracasts/generators/src/Commands/MigrationMakeCommand.php on line 16

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

Installation failed, reverting ./composer.json to its original content.

**Comment by tomasienrbc** [comment]
Why was this closed? I had this error too
