### ISSUE TITLE
ReflectionException with Laravel 5.5

### ISSUE THREAD

**Issue by captainkirkoff** [laracasts/Laravel-5-Generators-Extended#140]
Hi,
Laravel 5.5.2, Php 7.1.8.

When I try php artisan make:migration:schema I get the following:

 [ReflectionException]
  Method Laracasts\Generators\Commands\MigrationMakeCommand::handle() does not exist

tried both dev-master (1.1.3) and dev-master 1.1.4 (which is the one works with Laravel 5.4)

**Comment by uibar** [comment]
Not all commands should have a handle method by default? it's missing entirely in the package.

**Comment by uibar** [comment]
Yes, indeed the method was renamed, #138 fixes the issue.

**Comment by tabacitu** [comment]
Hi guys,

Jeffrey was kind enough to merge the PR, so we're now ready to go. A ```composer update``` should fix it for you guys. Also, I've tagged it as ```v1.1.4``` so you no longer need to require the ```dev-master```, you can use it like any other package.

Cheers!
