### ISSUE TITLE
 Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found

### ISSUE THREAD

**Issue by lloricode** [laracasts/Laravel-5-Generators-Extended#142]
im using laravel 5.5.3

![screenshot from 2017-09-13 20-05-32](https://user-images.githubusercontent.com/8251344/30376503-31b3e260-98bf-11e7-938c-ca41128ce44e.png)

**Comment by cytRasch** [comment]
Take a look at this commit:
[renamed AppNamespaceDetectorTrait to DetectsApplicationNamespace as p…](https://github.com/laracasts/Laravel-5-Generators-Extended/commit/c37b9904539c29dc652ff6d7f5019823b8d921c7)

Just follow the changes and everything works fine.

**Comment by OutRunner** [comment]
Thanks @cytRasch!

For anyone confused, once you've run `composer require laracasts/generators --dev` and have seen the error message the package will still be on your file system. You can just search your project for the `src/Commands/MigrationMakeCommand.php` file and make the changes the commit @cytRasch linked above. After that just run `composer require laracasts/generators --dev` again and it should all be working!

**Comment by johnsvenn** [comment]
Rather than changing the files you could include @tabacitu branch in composer rather than updating the files manually e.g.

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "repositories": [
        {
            "type":"vcs",
            "url":"https://github.com/tabacitu/Laravel-5-Generators-Extended.git"
        }
    ],
    "require-dev": {
        "laracasts/generators": "dev-package-autodiscovery",
    },

etc.

```

Update composer then run `composer update`

(works for me just now in Laravel 5.5.19)

**Comment by tabacitu** [comment]
Hi guys,

A PR has been merged that fixes this, so I'll close this - a ```composer update``` should fix it for you. Feel free to reopen the issue if you're still having this problem.

Cheers!

**Comment by tabacitu** [comment]
@johnsvenn - actually I'd rather you not use that repository, it was just a fork for a PR, so it most likely will get deleted. Jeffrey was kind enough to give me write access to _this_ repository, so I'll try to keep this reasonably up-to-date. You can use it like any other package now.

**Comment by johnsvenn** [comment]
@tabacitu - no problem. I was thinking just in terms of a quick fix. But, often quick fixes have a nasty habit of hanging around longer than they should!
