### ISSUE TITLE
Foreign key doesn't work correctly with id

### ISSUE THREAD

**Issue by trakons** [laracasts/Laravel-5-Generators-Extended#144]
- Laravel Version: 5.5.24
- PHP Version: 7.1
- Laravel-5-Generators-Extended Version: latest
- Command: php artisan make:migration:schema create_shop_table --schema="shopCategories_id:integer:foreign, title:string, body:text, price:integer, picture:text"

### Description:
I tried several times but laravel cannot migrate without these 
fixes

### Steps To Reproduce:
After `public function up()` add `Schema::enableForeignKeyConstraints();`

To the foreign column add `->unsigned()`
`$table->integer('shopCategories_id');` -> `$table->integer('shopCategories_id')->unsigned();`

In the attached picture you can see the result before and after my additions
<img width="1314" alt="screen shot 2017-12-09 at 12 37 13" src="https://user-images.githubusercontent.com/3083964/33795227-cee69bec-dcdd-11e7-82cc-29890eafa264.png">

**Comment by tabacitu** [comment]
Hi @trakons ,

Soo... _Id columns should be ```unsigned``` if artisan is configured to add foreign key constraints._ Do I understand you suggestion correctly? 

Cheers!

**Comment by tabacitu** [comment]
PR #165 got merged inside the ```v2``` branch. So that in Laravel 5.8+ we're always using ```unsignedBigIntegers``` just like the Laravel default. So I'm going to close this. Let me know if this still doesn't fix the issue and we'll reopen it.

Cheers!
