### ISSUE TITLE
Change 'Schema::drop()' in favor of 'Schema::dropIfExists()'

### ISSUE THREAD

**Issue by lexxyungcarter** [laracasts/Laravel-5-Generators-Extended#149]
- Laravel Version: ^5.2
- PHP Version: 7.0.0
- Laravel-5-Generators-Extended Version:
- Command: php artisan make:migration:schema create_foos_table  

### Description:
To keep it updated with the current Laravel migration templates, it would be nice to have the **drop()** method replaced with **dropIfExists**

### Steps To Reproduce:
Current: 
Schema::drop('table_name');

Suggestion:
Schema::dropIfExists('table_name');

**Comment by bogdankharchenko** [comment]
Opened a PR https://github.com/laracasts/Laravel-5-Generators-Extended/pull/154  https://github.com/laracasts/Laravel-5-Generators-Extended/pull/154/commits/d0b3d2e26482a5686a6f9b763c242aefb016a3a0

**Comment by tabacitu** [comment]
This got merged, so I'll close this. Thanks for the issue and PR @lexxyungcarter & @bogdankharchenko . You guys rock. Cheers!
