### ISSUE TITLE
make:migration:schema generates foreign constraints incorrectly

### ISSUE THREAD

**Issue by Kehet** [laracasts/Laravel-5-Generators-Extended#15]
command
```
php artisan make:migration:schema create_posts_table --schema="user_id:integer:foreign"
```
generates
```php
// ...
$table->increments('id');
$table->integer('user_id');
$table->foreign('user_id')->references('id')->on('users');
$table->timestamps();
// ...
```
expected output
```php
// ...
$table->increments('id');
$table->integer('user_id')->unsigned();
$table->foreign('user_id')->references('id')->on('users');
$table->timestamps();
// ...
```

since most probably foreign keys will be used with ``$table->increments('id');`` on other side

**Comment by DarkponyLtd** [comment]
Same as issue https://github.com/laracasts/Laravel-5-Generators-Extended/issues/12

The solution is: *user_id:integer:unsigned:foreign*

Documentation needs updating, but anyhow I would prefer to have this automated even without the unsigned option, it makes sense, doesn't it?
