### ISSUE TITLE
Differences in table names

### ISSUE THREAD

**Issue by m3pogrammer** [laracasts/Laravel-5-Generators-Extended#150]
Hello. Summary :

**php artisan make:migration:pivot tags items**
table name: **item_tag**
filename: 2018_01_22_140639_create_item_tag_pivot_table.php

**php artisan make:migration:pivot categories items**
table name: **category_item**
filename: 2018_01_22_140942_create_category_item_pivot_table.php

Why names are different?! 

I think Both should be `item_tag` and `item_category` ! But now they are different

**Comment by prinzt** [comment]
The names are generated alphabetically.
"php artisan make:migration:pivot a b" or "php artisan make:migration:pivot b a"
will always be a_b

**Comment by m3pogrammer** [comment]
Thanks for answer. but, why !?

**Comment by prinzt** [comment]
afaik it's a convention / considered best practice.
