### ISSUE TITLE
Class name problem

### ISSUE THREAD

**Issue by m3pogrammer** [laracasts/Laravel-5-Generators-Extended#151]
Hello, Summery:

Why class name is wrong after create pivot table?

`class **App\** extends Migration`

![problem](https://user-images.githubusercontent.com/35694231/35224974-34e084ea-ff9c-11e7-9b04-157f2390d986.png)

Thanks.

**Comment by bogdankharchenko** [comment]
opened a PR, https://github.com/laracasts/Laravel-5-Generators-Extended/pull/154

**Comment by danielptaylor** [comment]
Looks like a method call was missed. It works correctly when I make the following change in my installation.

in src/Commands/PivotMigrationMakeCommand.php at line 89

replace
 ` ->replaceClass($stub, $name);`
with
`  ->replaceClass($stub, $this->parseName($name));`

**Comment by tabacitu** [comment]
PR got merged a long time ago. Thank you for raising this @m3pogrammer & for fixing it @bogdankharchenko ! You guys rock!
