### ISSUE TITLE
Upgrading to Laravel 5.6 error with generators packagist

### ISSUE THREAD

**Issue by itepifanio** [laracasts/Laravel-5-Generators-Extended#159]
- Laravel Version: 5.6
- PHP Version: 7.1.3
- Laravel-5-Generators-Extended Version: 1.1
- Command: ` composer update ` 

### Description:

![screenshot from 2018-10-01 16-27-59](https://user-images.githubusercontent.com/6730205/46310910-0df9ac00-c597-11e8-8b7d-2a617e20ed0e.png)

### Steps To Reproduce:

Upgrade laravel from 5.5 to 5.6, run composer update

**Comment by tabacitu** [comment]
Hi @itepifanio ,

Looks like packagist had that package down for a little while. It happens sometimes, even for big names like Packagist. Hell, even for big names like Github :-)

I’m sure it’ll work if you try again, so I’ll close the issue.

Cheers!
