### ISSUE TITLE
Pivot tables not using bigInteger

### ISSUE THREAD

**Issue by mcardle** [laracasts/Laravel-5-Generators-Extended#168]
- Laravel Version: 5.8.0
- PHP Version: 7.3
- Laravel-5-Generators-Extended Version: 1.1.6
- Command: make:migration:pivot

### Description:
As of Laravel 5.8 the users table uses bigInteger (bigIncrements). If you follow that through out your application, then, when creating a pivot table the fields used are integer fields instead of bigInteger. When mixing datatype you cannot create foreign keys between them.

### Steps To Reproduce:
- Take a fresh copy of Laravel 5.8 or above
- Install the generator
- Create a migration for images called "image" with two fields "id" and "filepath"
- Create a pivot table using: ```php artisan make:migration:pivot user image```
- run ```php artisan migrate```
- Error now occurs.

### Fix
- Change generators/stubs/pivot.stub:16 to $table->bigInteger('{{columnOne}}_id')->unsigned()->index();
- Change generators/stubs/pivot.stub:18 to $table->bigInteger('{{columnTwo}}_id')->unsigned()->index();

**Comment by tabacitu** [comment]
Thank you for the comprehensive bug report @mcardle !

Fixed in https://github.com/laracasts/Laravel-5-Generators-Extended/pull/165 - merged, will be released shortly.
