### ISSUE TITLE
Table Name with underline _

### ISSUE THREAD

**Issue by timoteo7** [laracasts/Laravel-5-Generators-Extended#174]
- Laravel Version: 6.18
- PHP Version: 7.2
- Laravel-5-Generators-Extended Version: 1.1.8
- Command: `php artisan make:migration:pivot order_items package_modality_rate_detail`

### Description:

underline ' _ ' in command return error:

> "Call to undefined function Laracasts\Generators\Commands\studly_case()"

if i did without underline dont have error, but the name generated is incorrect

`php artisan make:migration:pivot orderItems packageModalityRateDetail`

### Steps To Reproduce:
`php artisan make:migration:pivot order_items package_modality_rate_detail`

**Comment by timoteo7** [comment]
#161

**Comment by tabacitu** [comment]
Updating to the latest version should fix it for you @timoteo7 . Let me know if a ```composer update``` doesn't do it for you.

Cheers!
