### ISSUE TITLE
 Call to undefined function Laracasts\Generators\Commands\camel_case()

### ISSUE THREAD

**Issue by bdjunayed** [laracasts/Laravel-5-Generators-Extended#175]
- Laravel Version: 7

 Call to undefined function Laracasts\Generators\Commands\camel_case()

**Comment by tabacitu** [comment]
Thanks for raising the issue @bdjunayed . I assume https://github.com/laracasts/Laravel-5-Generators-Extended/pull/176 fixes this - difficult to know from the little information you gave here. Let me know if that doesn't fix it, and I'll reopen the issue.

**Comment by bdjunayed** [comment]
You are so kind, its workng.
