### ISSUE TITLE
Need to upgrade with the laravel 7.

### ISSUE THREAD

**Issue by bdjunayed** [laracasts/Laravel-5-Generators-Extended#178]
- Laravel Version: 7

### Description: In pivot table need to upgrade with the laravel 7.

Need use this line,
```php
$table->foreignId('cat_id')->constrained()->onDelete('cascade');
            $table->index('cat_id');
```

instead of,
```php
$table->integer('cat_id')->unsigned()->index();
            $table->foreign('cat_id')->references('id')->on('cats')->onDelete('cascade');
```

**Comment by tabacitu** [comment]
Could you please explain the change in more detail? Why is this needed? What did you try to do and didn't work?

**Comment by bdjunayed** [comment]
Laravel 7 is supporting ```$table->foreignId('cat_id')->constrained()->onDelete('cascade');``` which is  quavelent with ``` $table->foreign('cat_id')->references('id')->on('cats')->onDelete('cascade');``` and so on. I think it would be good if we provide this convention.

**Comment by bdjunayed** [comment]
My point was, can we do 
```php$table->foreignId('cat_id')->constrained()->onDelete('cascade');
``` 
instead of 
```php
$table->integer('cat_id')->unsigned()->index();
$table->foreign('cat_id')->references('id')->on('cats')->onDelete('cascade');
```

**Comment by reynaldiaznan123** [comment]
@bdjunayed this schema: category_id:foreignId:constrained:onDelete('cascade')

**Comment by tabacitu** [comment]
Thanks for pitching in @reynaldiaznan123 ! Glad to see this is not actually an issue, that we can do that already.

Let me close the issue then.
