### ISSUE TITLE
V2 status ?

### ISSUE THREAD

**Issue by eightyfive** [laracasts/Laravel-5-Generators-Extended#179]
I see some activity on v2 back in March. What is the current v2 status?

**Comment by eightyfive** [comment]
How can we help?

Can we have a go at some of the [todos](https://github.com/laracasts/Laravel-5-Generators-Extended/projects/2#column-8253864) ?

What about the [in progress PRs](https://github.com/laracasts/Laravel-5-Generators-Extended/projects/2#column-8253865)? What's missing to make them "Done" ?

It would be great to some kind of target ETA.

Thanks!

**Comment by tabacitu** [comment]
Hi @eightyfive ,

> I see some activity on v2 back in March. What is the current v2 status?

WIP I guess. I would like to finish up v2 and launch it in 1-2 weeks. Especially if I get some help 😉 

> Can we have a go at some of the todos ?

Yes please! Any help is very much appreciated:
- submitting PRs for the "todos";
- even reviewing & testing the PRs under "in progress";

**Comment by eightyfive** [comment]
Ok thanks for the update.
