### ISSUE TITLE
seed stub not parsing {{class}} with seed name

### ISSUE THREAD

**Issue by drbroad** [laracasts/Laravel-5-Generators-Extended#18]
Hi,

Small issue: running a simple `php artisan make:seed users` results in no errors, but the output of `UsersTableSeeder.php` :

        use Illuminate\Database\Seeder;

        // composer require laracasts/testdummy
        use Laracasts\TestDummy\Factory as TestDummy;

        class {{class}} extends Seeder
        {
            public function run()
            {
                // TestDummy::times(20)->create('App\Post');
            }
        }

**Comment by laracasts** [comment]
Have you done a composer update lately? I've used this command countless times and have never seen that.
