### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by scwall** [laracasts/Laravel-5-Generators-Extended#192]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-5-Generators-Extended Version:
- Command:

### Documentation 
hello,

I tried the methods indicated in the documentation but this one did not work for a stupid reason, the generation is a biginteger as primary key with , can be changed in the documentation integer to BigInteger:foreign in the example for the creation of a foreign key.

I found outside of the documentation that it was necessary to use string(60) to specify the varchar size.

**Comment by tabacitu** [comment]
Hi @scwall ,

Thanks for the heads-up. I wasn't able to get any errors though. Ran the examples in the docs, worked fine for me.

Which example did you have problems with? What was the error more specifically?

Cheers!
