### ISSUE TITLE
'viewAny' policy documentation is ambivalent

### ISSUE THREAD

**Issue by TeNNoX** [laracasts/Laravel-5-Generators-Extended#193]
> Determine whether the user can view any models.

This can be understood as:
- whether the user can access **all of them**
- when you return false, they **can't access any**

**Laravel Version**: 7.X
**Laravel-5-Generators-Extended Version**: 2.0.0

**Comment by tabacitu** [comment]
Thanks @TeNNoX - can you point me where you found this? Couldn't find it myself.

**Comment by TeNNoX** [comment]
1. Run `artisan make:policy -m X XPolicy`
2. See the following code:

```php
    /**
     * Determine whether the user can view any models.
     *
     * @param  \App\Models\User  $user
     * @return mixed
     */
    public function viewAny(User $user)
    {
        //
    }

    /**
     * Determine whether the user can view the model.
     *
     * @param  \App\Models\User  $user
     * @param  \App\Models\X  $x
     * @return mixed
     */
    public function view(User $user, X $x)
    {
        //
    }
```

**Comment by TeNNoX** [comment]
You're right, it's in the laravel main repo... Sorry:
https://github.com/laravel/framework/blob/28e0f61bba1cbc727383d183b7116eb723de7660/src/Illuminate/Foundation/Console/stubs/policy.stub

**Comment by TeNNoX** [comment]
They don't seem to like it though :P
https://github.com/laravel/framework/issues/36840
