### ISSUE TITLE
Why is is it called "schema"?

### ISSUE THREAD

**Issue by joelmellon** [laracasts/Laravel-5-Generators-Extended#198]
Why is the `make:migration:schema` command and its option `--schema` called that?

They have nothing to do with database schemas. They define the _structure_ of tables.

In MySQL a schema is essentially just a [database](https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_schema). They're practically synonymous. This is true for SQLite as well.

> In MySQL, physically, a schema is synonymous with a database. You can substitute the keyword SCHEMA instead of DATABASE in MySQL SQL syntax, for example using CREATE SCHEMA instead of CREATE DATABASE.

In PostgreSQL (and almost every other RDMS) a database contains schema(s) which contains tables. again, nothing to do with table structure. https://stackoverflow.com/a/5323750

Anyway, I expected this package to give me a migration that would create a MySQL schema/database, not a "quicker" way to create a table and its columns.

A better name might be `make:migration:structure` no?

**Comment by cheesegrits** [comment]
Erm ...

https://en.wikipedia.org/wiki/Database_schema

> In a [relational database](https://en.wikipedia.org/wiki/Relational_database), the schema defines the [tables](https://en.wikipedia.org/wiki/Table_(database)), [fields](https://en.wikipedia.org/wiki/Field_(computer_science)), [relationships](https://en.wikipedia.org/wiki/Relational_model), [views](https://en.wikipedia.org/wiki/View_(database)), [indexes](https://en.wikipedia.org/wiki/Index_(database)), [packages](https://en.wikipedia.org/wiki/Software_package_(installation)), [procedures](https://en.wikipedia.org/wiki/Stored_procedure), [functions](https://en.wikipedia.org/wiki/Subroutine), [queues](https://en.wikipedia.org/wiki/Queue_(data_structure)), [triggers](https://en.wikipedia.org/wiki/Database_trigger), [types](https://en.wikipedia.org/wiki/Data_type), [sequences](https://en.wikipedia.org/wiki/Sequence), [materialized views](https://en.wikipedia.org/wiki/Materialized_view), [synonyms](https://en.wikipedia.org/wiki/Synonym_(database)), database links, [directories](https://en.wikipedia.org/wiki/Directory_(file_systems)), [XML schemas](https://en.wikipedia.org/wiki/XML_schema), and other elements

**Comment by joelmellon** [comment]
Fair enough. I'm still on the hunt for a package that creates databases with configuration options, eg. CHARACTER SET, COLLATE, ENCRYPTION, etc. If you know of one... 😉
