### ISSUE TITLE
Error when creating migration

### ISSUE THREAD

**Issue by mikeerickson** [laracasts/Laravel-5-Generators-Extended#2]
When creating a basic migration (with schema) using following

<pre>

</pre>

I receive the following error

http://d.pr/i/18lPz2

**Comment by mikeerickson** [comment]
Oops, hit send too soon (here is the actual command line)



<pre>

php artisan make:migration:schema create_dogs_table --schema="type:string:unique, gender:boolean"


</pre>

**Comment by slayerfat** [comment]
next time, you can edit your message to append the missing code.

anyway, the error link is 404, link again

**Comment by mikeerickson** [comment]
@slayerfat not sure what happened there (appears with in Droplr admin)?

at any rate, I cant reproduce issue now (all is working as expected) so I am gonna close this puppy
