### ISSUE TITLE
How to make template scaffold ?

### ISSUE THREAD

**Issue by azizgithub** [laracasts/Laravel-5-Generators-Extended#20]
Hay, I want to create my own template (like generate:scaffold in generator L4) ? How i do for this ?
Thanks :)

**Comment by lorvent** [comment]
I am also looking for this

if you can make scaffold... this package will become a hit like l4's

**Comment by sebastiaanluca** [comment]
Also kind of missing this great feature from Laravel 4 :)

**Comment by vaughany** [comment]
:+1:  I've just started looking at the Laravel framework; would love to see `generate:scaffold` in the L5 version of your generators. (I have previously used CakePHP's `bake` command which is an amazing way to hit the ground running.)

**Comment by fcaivano** [comment]
+1 Interested also

**Comment by tabacitu** [comment]
Sorry for closing this, guys. Jeffrey doesn't really have time to maintain this package anymore, so please don't expect more features. He's been kind enough to give me write access to bring it up-to-date and make it work on L5.4 and L5.5, but I can't allocate a lot of time for this myself, I have [12+ projects in Backpack](https://github.com/laravel-backpack/) that take priority. 

Thanks for understanding. Cheers!
