### ISSUE TITLE
Adding a foreign column causes duplicate dropColumn

### ISSUE THREAD

**Issue by EspadaV8** [laracasts/Laravel-5-Generators-Extended#21]
When creating a scheme with a foreign key the migration has a duplicated `dropColumn` line, e.g. after running this command `php artisan make:migration:schema add_phone_to_users_table --schema="phone:integer:unsigned:foreign"` the following migration is created

``` php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddPhoneToUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function(Blueprint $table) {
            $table->integer('phone')->unsigned();
            $table->foreign('phone')->references('id')->on('phones');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function(Blueprint $table) {
            $table->dropColumn('phone');
            $table->dropColumn('phone');
        });
    }
}
```

**Comment by jdavidbakr** [comment]
It should be creating dropForeign instead of dropColumn for the first line in the down closure.

**Comment by jdavidbakr** [comment]
Fixed https://github.com/laracasts/Laravel-5-Generators-Extended/pull/59

**Comment by joelcuevas** [comment]
I just keep running on the same error every few weeks... Any update on this?

**Comment by tabacitu** [comment]
Thank you for raising this issue @EspadaV8 . Let's close this in favour of PR #59 . Let me know what you think about the solution there. I would love to merge this into v2 https://github.com/laracasts/Laravel-5-Generators-Extended/pull/170 soon.

Cheers!
