### ISSUE TITLE
Running artisan fresh after installing this package, will unregister it.

### ISSUE THREAD

**Issue by gin93r** [laracasts/Laravel-5-Generators-Extended#23]
Not an "issue" but a warning. If you follow the instructions and add the provider to `app/Providers/AppServiceProvider.php`, upon running `artisan fresh`, you will have to re-add the provider as `artisan fresh` clears that out.

Also - if there's a better place to add comments like this, please advise me of where. :)

**Comment by tabacitu** [comment]
Update: the package uses Laravel's autoregister feature nowadays, so it's no longer an issue.

Closing - thank you for submitting this to let people know @gin93r !
Cheers!
