### ISSUE TITLE
Command make:view?

### ISSUE THREAD

**Issue by sahibalejandro** [laracasts/Laravel-5-Generators-Extended#24]
there are plans to implement the `make:view` command like `generate:view` was on way/generators package?

**Comment by ieo** [comment]
Was wondering the same thing

**Comment by sahibalejandro** [comment]
You can use my gists https://gist.github.com/sahibalejandro/1030d43259a6fe95f79f
Just update the namespace and register the command on your Laravel proyect and use `view:make`

**Comment by tabacitu** [comment]
Sorry @sahibalejandro  but this is our of scope for this package. It only aims to help generate files that are database-specific, by defining the schema in the command-line too. And the view isn't db-specific.

Cheers!
