### ISSUE TITLE
Version constraint error when installing

### ISSUE THREAD

**Issue by jorenmartijn** [laracasts/Laravel-5-Generators-Extended#25]
Hi, I've tried installing this using the composer command you provided and I get these errors: 
 `[RuntimeException]                                                           
  Could not load package dragonrun1/phpspec in http://packagist.org: [Unexpec  
  tedValueException] Could not parse version constraint ^1.0.1: Invalid versi  
  on string "^1.0.1"`  
`[UnexpectedValueException]                                                  
  Could not parse version constraint ^1.0.1: Invalid version string "^1.0.1"`
My composer.json already seems to contain   `"phpspec/phpspec": "~2.1",` out of the box on L5, so could there be some kind of conflict between the two?

Any help on this would be great!

**Comment by ilkovich** [comment]
Just ran into this myself. Apparently carets have been recently introduced in composer. You need to run this first: 

```shell
composer selfupdate
```

**Comment by jorenmartijn** [comment]
Strange, because I think I did that quite recently. ​I'll try it anyway. Thanks!

**Comment by jorenmartijn** [comment]
Well, it seems to have worked!


Maybe it's a good idea to update the readme to include this issue and the solution? Just a thought.



​I can't be the only one who experienced this and updating composer wasn't my first idea while trying to troubleshoot the error. 



Op dinsdag 24 mrt. 2015 om 19:14 schreef Joren de Graaf <jorendegraaf@gmail.com>:



Strange, because I think I did that quite recently. ​I'll try it anyway. Thanks!

**Comment by vinkla** [comment]
Its good that you made it work again. Though, I don't agree this should be in the readme. This is not an issue specific for this package. This should be closed.
