### ISSUE TITLE
generate:scaffold not working at all

### ISSUE THREAD

**Issue by itsazzad** [laracasts/Laravel-5-Generators-Extended#26]
php artisan generate:scaffold not working at all. Its throwing error after:$ php artisan generate:scaffold {resource}

Do you want me to create a {resource} model? [yes|no] yes

[InvalidArgumentException] The "--templatePath" option requires a value.

But in the list of options after executing php artisan generate:scaffold --help there is no --templatePath And again if I try with php artisan generate:scaffold {resource} --templatePath

[RuntimeException]
The "--templatePath" option does not exist.

**Comment by laracasts** [comment]
Wrong package.

**Comment by lsc20051426** [comment]
which means If i am using Laravel 5, I cann't generate model from table anymore?
Or i need to use Laravel 4 Generators package and Laravel 5 Generator Extended at the same time?
