### ISSUE TITLE
Proposal: Suggest laracasts/TestDummy in composer.json

### ISSUE THREAD

**Issue by Niban** [laracasts/Laravel-5-Generators-Extended#29]
I created my first seed files in Laravel yesterday. The code I wrote to seed the database would have been way easier if I remembered about your laracasts/TestDummy package. I propose you add it as a suggested package in composer.json. That would have really helped me. 

Let me know what you think.

**Comment by laracasts** [comment]
Hmm - only thing is that it's not really related to the process of generating files at all.

**Comment by Niban** [comment]
Fair enough. That's why I wanted to ask. Thanks!
