### ISSUE TITLE
missing documentation -- defining new column length

### ISSUE THREAD

**Issue by shawnfromportland** [laracasts/Laravel-5-Generators-Extended#30]
Hello, If i want to add a new column with migrations something like:

```
make:migration:schema add_password_to_users_table --schema="password:varchar"
```

how do I specify the field _length_? just looking for a reference sheet for the syntax. thanks

**Comment by Niban** [comment]
You do it like this:

```
make:migration:schema add_password_to_users_table --schema="password:string(60)"
```

**Comment by zhuzhichao** [comment]
@Niban  Thank you . You are right.
