### ISSUE TITLE
Generators not showing

### ISSUE THREAD

**Issue by driesg** [laracasts/Laravel-5-Generators-Extended#31]
I followed the steps as listed in the readme.md but the generators are not showing when I run ```php artisan```

When I add the service provider to `config/app.php`, they do show ?

**Comment by vinkla** [comment]
I'm not sure what your question is but here is an answer anyway. You have to add it to the `config/app.php` to register that the commands exists before you can use them in the command line.

**Comment by driesg** [comment]
Sorry long night, should've been more clear. Step 2 of readme.md states:

    You'll only want to use these generators for local development, so you don't want to update the production providers array in config/app.php. Instead, add the provider in app/Providers/AppServiceProvider.php ...

Which is what I did, after step 1 of course.

I actually just realised that the generators ARE available when I ssh into my homestead box but NOT when I just cd to the project folder on Mac OS X. **Is this expected behaviour? **

The above is happening on my Macbook. On my iMac at work I **can** use them from the Mac OS command line. 
So I'm just confused as to what is correct? Should these generators be used inside homestead box or can I use them from the OS X?

**Comment by vinkla** [comment]
Okay, now its more clear what you're asking. Could you maybe paste the `AppServiceProvider` class in this thread?

**Comment by driesg** [comment]
sure, here you go
```
<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        if ($this->app->environment() == 'local') {
            $this->app->register('Laracasts\Generators\GeneratorsServiceProvider');
        }
    }
}
```

**Comment by vinkla** [comment]
Have you set the `APP_ENV` variable to local in your `.env` file?

**Comment by driesg** [comment]
yes

APP_ENV=local
APP_DEBUG=true
APP_KEY=XYZ

**Comment by vinkla** [comment]
Thats strange, I do this myself in [this project](https://github.com/larahunt/larahunt/blob/master/app/Providers/AppServiceProvider.php) without any problem at all.

**Comment by driesg** [comment]
Something must've been wrong with the `.env` file.Everything works after deleting and recreating it. Thanks for your help!
