### ISSUE TITLE
make:migration:schema model is empty

### ISSUE THREAD

**Issue by cskiwi** [laracasts/Laravel-5-Generators-Extended#32]
hi,

I tried running the following command:
`hp artisan make:migration:schema create_clubs_table --schema="name:string, email:string, abbreviation:string:nullable"`

And this created the right migration, but the model file it created was empty:

``` php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Club extends Model {

    //

}
```

I don't know if this is intended or not, but just wanting to point this out :)

**Comment by avlastenok** [comment]
If what you pasted was in the model file then I don't see an issue here as this is expected behavior.

**Comment by bastiaan89** [comment]
What would you expect to be in the model class? Just by extending ``Model``, they can be used already.

**Comment by davestewart** [comment]
It would be cool if it populated the PHPDoc comments like so:

```/**
 * Club Model
 *
 * @property 	int 	id
 * @property 	string 	name
 * @property 	string 	email
 * @property 	string 	abbreviation
 * @property 	Carbon 	created_at
 * @property 	Carbon 	updated_at
 */
```

**Comment by tabacitu** [comment]
I think it's a great practice, thank you for sharing @davestewart . But I'm afraid it's not very DRY - you'd then have to change this there if you manually change them in the migration...

Sorry for closing this, guys. Jeffrey doesn't really have time to maintain this package anymore, so please don't expect more features. He's been kind enough to give me write access to bring it up-to-date and make it work on L5.4 and L5.5, but I can't allocate a lot of time for this myself, I have [12+ projects in Backpack](https://github.com/laravel-backpack/) that take priority. 

Thanks for understanding. Cheers!
