### ISSUE TITLE
Generate function with Artisan !!?

### ISSUE THREAD

**Issue by Daoudbk** [laracasts/Laravel-5-Generators-Extended#35]
Hi everyone,
 I'm looking for a way to generate code function(php ) from dashboard with laravel or just with php !!! Any help will be great :) 

or a way to generate function with artisan !
Thanks in advance

**Comment by tabacitu** [comment]
Sorry @Daoudbk but that's out of scope for this project. I assume you've either figured it out by now (since 2015) or moved on 🤣 so I'll close the issue.

Cheers!
