### ISSUE TITLE
no more generate:resource generator ?

### ISSUE THREAD

**Issue by sangimed** [laracasts/Laravel-5-Generators-Extended#37]
There was a useful command in the previous version of the plugin that allows us to create a "REST ressource" as in the screenshot but i couldn't find it in the Laravel 5 version of the plugin... ?

http://i.imgur.com/3QD7Mim.png

Thanks.

**Comment by phroggyy** [comment]
Hey @sangimed, this is because Laravel 5 will create RESTful resource controllers by default when you run `php artisan make:controller`. If you don't want a RESTful controller, you have to pass the optional `--plain` parameter to create a controller without methods

**Comment by sangimed** [comment]
okay got it thank you :)

2015-06-24 8:16 GMT+01:00 Leo Sjöberg <notifications@github.com>:

**Comment by pkunze** [comment]
also see #26
