### ISSUE TITLE
Generating pivots with tables that contain underscores in name produces incorrect class name

### ISSUE THREAD

**Issue by TomCawthorn** [laracasts/Laravel-5-Generators-Extended#38]
Hello!

I've had a go at running this:

```

 php artisan make:migration:pivot test_table foo_table

```

and the generated migration had a class name of CreateBar_tableFoo_tablePivotTable.

I'm running on Laravel 5 and pulled in (as per instructions) generators using:

```

 composer require laracasts/generators --dev

```

This created 

```

"laracasts/generators": "^1.1"


```

in my composer.json

Thanks!

Tom

**Comment by jorenvanhee** [comment]
I'm also having this issue

**Comment by amin101** [comment]
you should remove underscore from class name manualy
so it would be : CreateBartableFootablePivotTable
