### ISSUE TITLE
model=false flag not working

### ISSUE THREAD

**Issue by joarobles** [laracasts/Laravel-5-Generators-Extended#41]
I've created my migration using the following command, 
Even the flag is set a Model 'EncuentrosTarjeta.php' is created under "app" folder:

```
php artisan make:migration:schema create_encuentros_tarjetas_table --schema="encuentro_id:integer:unsigned:foreign" --model=false
```

**Comment by dojorob76** [comment]
+1, --model=false is not honored at all.

**Comment by arifmahmudrana** [comment]
Same here not working

**Comment by EspadaV8** [comment]
--model=0 works. It looks like 'false' doesn't get cast to a boolean but it treated as a string

**Comment by nonDeath** [comment]
--model=0 works. But the #50 issue is more clear.

**Comment by RanZix** [comment]
@nonDeath, thank you for solution. Was facing same problem.

**Comment by sandeep514** [comment]
Artisan::call('make:migration:schema',[
								'--model'=>false,
                                'name'=>'create_'.$org->id.'_users',
                                '--schema'=>'name:string, email:string:unique, password:string, address:string:nullable,
                                phone:integer:nullable, approve:integer:default(0)'
                            ]);


        Artisan::call('migrate');

**Comment by tabacitu** [comment]
Closing, as it's working with ```model=0```.
