### ISSUE TITLE
Generators package with Lumen?

### ISSUE THREAD

**Issue by simbeto** [laracasts/Laravel-5-Generators-Extended#44]
does 
Laravel-4-Generators and this package works well with 'Lumen', the laravel's micro framework?

**Comment by lagseeing** [comment]
Lumen is based on laravel 5 not laravel 4

**Comment by deepu9** [comment]
So lagseeing, you mean, I can use Laravel 5 Generators for Lumen 5?

**Comment by tabacitu** [comment]
Yes you should be able to use it just fine!
