### ISSUE TITLE
Pivot doesn't substitute class name.

### ISSUE THREAD

**Issue by nardev** [laracasts/Laravel-5-Generators-Extended#46]
Command:

$ ./artisan make:migration:pivot somethings otherthings
Migration created successfully.      

Generates:

<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class {{class}} extends Migration
{
    /**
     \* Run the migrations.
     *
     \* @return void
     */
    public function up()
    {
        Schema::create('otherthing_something', function(Blueprint $table) {
            $table->integer('otherthing_id')->unsigned()->index();
            $table->foreign('otherthing_id')->references('id')->on('otherthings')->onDelete('cascade');
            $table->integer('something_id')->unsigned()->index();
            $table->foreign('something_id')->references('id')->on('somethings')->onDelete('cascade');
        });
    }

```
/**
 * Reverse the migrations.
 *
 * @return void
 */
public function down()
{
    Schema::drop('otherthing_something');
}
```

}

**Comment by nardev** [comment]
same for seed too

**Comment by jakecleary** [comment]
:+1:  I'm getting the same issue.

I'm guessing this is a simple fix? Might be worth one of us PRing it @nardev. I'll see if I have time this weekend.

**Comment by lagseeing** [comment]
I'll try to submit a PR

**Comment by Houbsi** [comment]
+1 I just encountered the same issue.

**Comment by summermick** [comment]
I'm using php 5.6.11, have the problem too.
I wonder if anyone has this issue with php 5.5.*

**Comment by gcphost** [comment]
Reported here:
https://github.com/laracasts/Laravel-5-Generators-Extended/issues/51

Said was fixed, bad link, not fixed when I tried 3 days ago.

Commenter said this branch works:
https://github.com/hiendv/Laravel-5-Generators-Extended/tree/fix/pivot-dummy-classname

**Comment by Dargus77** [comment]
Same issue here.

**Comment by ikkentim** [comment]
This was already fixed in e4820fdb0b2dd5ff5b24bacf3315aae0986cd51d, but no release has been made since.

**Comment by lagseeing** [comment]
Yeah it hasn't been tagged.

**Comment by tabacitu** [comment]
Closing since this has been tagged a long time ago. Thanks for pitching in everyone!
