### ISSUE TITLE
error when require the package

### ISSUE THREAD

**Issue by Rami-Sohail** [laracasts/Laravel-5-Generators-Extended#5]
when i put this command

composer require 'laracasts/generators' --dev

 i have this error

 [InvalidArgumentException]
  Could not find package 'laracasts/generators' at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

what's the problem ? thank you

**Comment by rattfieldnz** [comment]
Did you use Composer to create your Laravel app, or Laravel's own app creating tool? I created a test project with Laravel's tool, issued your 'composer require ...' command, and didn't see any errors at all. I only came across this yesterday so I can't give anything definitive - I'm not sure if the laracasts generators require any special dependencies of some sort.

Here's a screenshot of the test project creation, with your composer command:
![capture](https://cloud.githubusercontent.com/assets/2468863/6407280/b1363826-bea1-11e4-9acf-28daee0ab7fb.PNG)

**Comment by laracasts** [comment]
Yeah - haven't heard of any others with this issue..

**Comment by enigmatic-user** [comment]
Same problem here, see screenshot. I tried it on a Windows 7 machine.

![laracasts-generators-install-error](https://cloud.githubusercontent.com/assets/434408/6428578/98355534-bfa8-11e4-9d38-a86f9bcb7c73.png)

Omitting the single quotation marks (I had copied the complete line from the readme page) lead to success. Maybe it would be good to change this in the readme.md.

**Comment by nhimbkno1** [comment]
Please change :
```
composer require 'laracasts/generators' 
```
to :
```
composer require "laracast/generators"
```

**Comment by lesterfibla** [comment]
I have the same issue in my win7+xampp

Laravel install 10 minutes ago (then, i have the v5) via composer

**Comment by rdharma** [comment]
I'm having the same issue...

**Comment by mikeerickson** [comment]
Remove quotest, call as

composer require laracasts/generators

**Comment by lesterfibla** [comment]
Perfect!!!
Without the quotes its works perfect.

Thanks

**Comment by enigmatic-user** [comment]
Hm, isn't that what I wrote above?  ;)

**Comment by slavensaka** [comment]
Changing:

composer require 'laracasts/generators' 
to :

composer require "laracast/generators"

Works perfectly!

**Comment by rdharma** [comment]
Thank you all for your help.
