### ISSUE TITLE
Got this error when creating migrations

### ISSUE THREAD

**Issue by binalfew** [laracasts/Laravel-5-Generators-Extended#6]
[InvalidArgumentException]                   
  The "--no-migration" option does not exist.

I did not even pass the --no-migration 

Any idea?

Thanks

**Comment by keithmclaughlin** [comment]
I also got the error mentioned above and did not pass the -no-migration either.

```PHP
Migration created successfully.
exception 'InvalidArgumentException' with message 'The "--no-migration" option does not exist.' in C:\wamp\www\laravel-5\vendor\symfony\console\Symfony\Component\Console\Input\ArrayInput.php:177
```

**Comment by laracasts** [comment]
You need to do a composer update to get the latest version of Laravel.
