### ISSUE TITLE
unexpected '{' while creating Pivot

### ISSUE THREAD

**Issue by janokary** [laracasts/Laravel-5-Generators-Extended#63]
I try to create a pivot:

    php artisan make:migration:pivot campaigns campaignresponses

The migration file is created but when I run 

    php artisan migrate

I get

    [Symfony\Component\Debug\Exception\FatalErrorException]        
    syntax error, unexpected '{', expecting identifier (T_STRING)
  
What happend is that in migration file in line 6 the class name was not created an left as is

    class {{class}} extends Migration

**Comment by janokary** [comment]
After that I manually named the class

    CreateCampaignresponseCampaignPivot
and run

    composer dump-autoload

the class is now in autoload_classmap.php
But now I am getting

    Class 'CreateCampaignresponseCampaignPivotTable' not found in vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 324

**Comment by shanecp** [comment]
I'm seeing the same issue as well. Using `dev-master` branch.

**Comment by ikkentim** [comment]
See #53

**Comment by JeffreyWay** [comment]
#53 merged. Closing.
