### ISSUE TITLE
how can i use `generate:resource`

### ISSUE THREAD

**Issue by nasirkhan** [laracasts/Laravel-5-Generators-Extended#66]
In the previous repository there was an option to use the following command. can you please tell me is there any way to this in this extended generator? 
`php artisan generate:resource`

**Comment by jackkeller** [comment]
I'm totally new to Laravel but I saw the resource generator too and was amazed, I know one can do the individual commands but getting up and running that'd be helpful to see all the files needed for a model/etc

**Comment by pkunze** [comment]
also see #26

**Comment by tabacitu** [comment]
I believe you're looking for the Laravel 4 generators, those had the ```generate:resource``` command afaik. Either way, that's not relevant today in 2020 so I'll close this issue 😄 Sorry you didn't get answered @nasirkhan .

Cheers!
