### ISSUE TITLE
Pivot doesn't render the class name

### ISSUE THREAD

**Issue by rephiscorth** [laracasts/Laravel-5-Generators-Extended#69]
The output migration seems fine except for the class declaration, it doesn't replace the class name and this is the output:
```
class {{class}} extends Migration
```

The command was run like this: (The README didn't said you need to specify a class name, just the 2 table names)
```
$ php artisan make:migration:pivot users stores
```

Dev dependency on composer.json
```
"laracasts/generators": "^1.1",
```

**Comment by miadzadfalah** [comment]
see this change
https://github.com/laracasts/Laravel-5-Generators-Extended/pull/61

**Comment by ikkentim** [comment]
Or #53

**Comment by fwartner** [comment]
Getting stil the same error.

**Comment by ikkentim** [comment]
Are you running the version on master?

**Comment by fwartner** [comment]
Yep. Fixed it now by hand..  Works
