### ISSUE TITLE
when a pivot table is created, it gives wrong class name

### ISSUE THREAD

**Issue by unclepickles** [laracasts/Laravel-5-Generators-Extended#71]
hello Jeffery
having used this generator to create a pivot table, it did everything correct except that it gave:
class {{class}} extends Migration as the header with classname not being specified, perhaps it didn't replace the variable, perhaps it's a setup problem here but everything else is working fine.

Thanks

**Comment by ikkentim** [comment]
This was already fixed in e4820fdb0b2dd5ff5b24bacf3315aae0986cd51d, but no release has been made since.

**Comment by unclepickles** [comment]
thanks
