### ISSUE TITLE
I got this strange behaviour when generating the migrations. 

### ISSUE THREAD

**Issue by binalfew** [laracasts/Laravel-5-Generators-Extended#8]
If you run the generator command without putting a space after each of the coma separated list of the schema fields like this:
php artisan make:migration:schema create_employees_table --schema="first_name:string,last_name:string"

the generated migration file will be: $table->string,last_name('first_name')->string() which is not right.

Where as you add the space after the comma you will get the correct migration file like so:
$table->string('first_name');
$table->string('last_name');

I think there is a small bug in there.

Thanks.

**Comment by kadeprice** [comment]
That's how it was with the L4 Generator. I assume the script knows it's a new line because there is a space. You can't do it on the comma because then this wouldn't work 
--schema="amount:double(15,2), customer_id:integer:index, customer_id:foreign:references('id'):on('customers'):onDelete('cascade')"

It would start a new line at (15,2). So the space is how it knows to start a new column.

**Comment by laracasts** [comment]
Yeah - it's tough. I need *some* kind of split point for the regular expression. I've spent a lot of time trying to find a way to make this optional, but no dice.

The primary issue is that you can do:

```
--schema="username:string, age:integer"
```

If it were just this, then we could make the ,[space] optional. But the user can also pass arguments:

```
--schema="username:string, amount:decimal(1,2)
```

So, if somebody knows how to split that up into chunks, while allowing no spaces between each field:column,  please do let me know. I haven't been able to figure out how. 

The regex would need to give me, using the example above, an array with two items:

- username:string
- amount:decimal(1,2)

**Comment by Niban** [comment]
I did some searching and found how to separate using commas, as long as they weren't in parenthesis. Did some testing and this works for me:


    $preg_split = preg_split('/,(?![^()]*+\\))/', $schema);
    return array_map("trim", $preg_split);

I had to run trim on the array to get rid of the spaces that may appear in front.

**Comment by laracasts** [comment]
So this is fixed and merged now.

Thanks, all.
