### ISSUE TITLE
(php artisan) Causes an Error in Laravel 5.2

### ISSUE THREAD

**Issue by shawnsandy** [laracasts/Laravel-5-Generators-Extended#81]
Can anyone help, I am getting an error when I run `php artisan` 

``` php
  [ReflectionException]                                
  Class Illuminate\Foundation\Composer does not exist 
```

had to remove this line to get php artisan to work

``` php
    if ($this->app->environment() == 'local') {
        $this->app->register('Laracasts\Generators\GeneratorsServiceProvider');
    }
```

**Comment by BorderlandsFan** [comment]
Same error. Waiting for the fix.

**Comment by inpariswithyou** [comment]
Also get the same error and would like a fix!

**Comment by ivanvermeyen** [comment]
It's just this reference to Composer:

https://github.com/laracasts/Laravel-5-Generators-Extended/blob/master/src/Commands/MigrationMakeCommand.php#L8

As Laravel's upgrade says:

"The Illuminate\Foundation\Support\Composer class has been moved to Illuminate\Support\Composer."

**Comment by mikeritter** [comment]
For the time being:

\vendor\laracasts\generators\src\Commands\MigrationMakeCommand.php

line 9

change to `use Laracasts\Generators\Migrations\NameParser;`

**Comment by tfortier** [comment]
I actually had to change line 8 of this file : 

\vendor\laracasts\generators\src\Commands\MigrationMakeCommand.php

to this ```use Illuminate\Support\Composer;``` in order to solve the error message.

**Comment by firescript** [comment]
Thanks guys! Big help :+1: on the quick fix, @tfortier worked for me.

**Comment by xiaolp** [comment]
replace use Illuminate\Foundation\Composer;
to
use Illuminate\Support\Composer; 

ScaffoldMakeCommand.php

**Comment by rvanbaalen** [comment]
Just starting the migration from 5.1* to 5.2 and this is still an issue apparently. Why hasn't this been addressed yet?

**Comment by LourensThalen** [comment]
Wondering the same. Keeps giving errors, even when I want to switch back to 5.1 :(

                                                       
  [ReflectionException]                                
  Class Illuminate\Foundation\Composer does not exist

**Comment by SoeThandarAung** [comment]
Hello, Can anyone help me? When I run php artisan , I got
BadMethodCalException error and
Call to undefined method [RegisterSyncsTableConnector]

**Comment by kevosomi** [comment]
To solve this issue please find "Illuminate\Foundation\Composer" in your entire project and replace with "Illuminate\Support\Composer". That should fix the problem. Worked in my case.

**Comment by rvanbaalen** [comment]
By searching for `Illuminate\Foundation\Composer` in my vendor folder, I found an incompatible package which was causing this error.
