### ISSUE TITLE
Scaffold

### ISSUE THREAD

**Issue by ryangurn** [laracasts/Laravel-5-Generators-Extended#85]
Is there a scaffold command like there was in laravel 4.2?

**Comment by dustinleblanc** [comment]
@JeffreyWay seeing as there is none, and it seems useful, would you like contributions to add that functionality? 

I remember listening to a recent laravel podcast in which you, Taylor, and Matt discussed PR's with no advanced notice and I'd like to avoid being part of the crowd :)

I'd like to volunteer some time to work on this if you desire to add it.

**Comment by Maidomax** [comment]
+1

**Comment by Braunson** [comment]
Any updates on this?

**Comment by tabacitu** [comment]
Sorry for closing this, guys. Jeffrey doesn't really have time to maintain this package anymore, so please don't expect more features. He's been kind enough to give me write access to bring it up-to-date and make it work on L5.4 and L5.5, but I can't allocate a lot of time for this myself, I have [12+ projects in Backpack](https://github.com/laravel-backpack/) that take priority. 

Thanks for understanding. Cheers!
