### ISSUE TITLE
this work laravel 5.2?

### ISSUE THREAD

**Issue by ErkinAkbudak** [laracasts/Laravel-5-Generators-Extended#86]
hi. this plugin is work laravel 5.2?
I say
composer require way/generators --dev
Console say:
 [Composer\Repository\InvalidRepositoryException]  
  Invalid repository data in C:\xampp\htdocs\erciyesgunisi_laravel/vendor/composer/installed.json, packages could not
   be loaded: [Seld\JsonLint\ParsingException] "C:\xampp\htdocs\erciyesgunisi_laravel/vendor/composer/installed.json"
   does not contain valid JSON  
  Parse error on line 1:                                                        

  ^  
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['        

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

**Comment by xitude** [comment]
See #81
