### ISSUE TITLE
Error in laravel 5.2

### ISSUE THREAD

**Issue by shirone** [laracasts/Laravel-5-Generators-Extended#89]
Warning: include(C:\laragon\www\pathravel\vendor/symfony/console/Input/ArgvInput.php): failed to open stream: No such file or directory in C:\laragon\www\pathravel\vendor\composer\ClassLoader.php on line 412

Call Stack:
    0.0000     130152   1. {main}() C:\laragon\www\pathravel\artisan:0
    0.0520    1934904   2. spl_autoload_call() C:\laragon\www\pathravel\artisan:34
    0.0520    1934960   3. Composer\Autoload\ClassLoader->loadClass() C:\laragon\www\pathravel\artisan:34
    0.0520    1934960   4. Composer\Autoload\includeFile() C:\laragon\www\pathravel\vendor\composer\ClassLoader.php:301

Warning: include(): Failed opening 'C:\laragon\www\pathravel\vendor/symfony/console/Input/ArgvInput.php' for inclusion (include_path='C:\laragon\www\pathravel\vendor/phpseclib/phpseclib/phpseclib;.;C:/laragon/bin/php/php-5.5.29/PEAR') in C:\laragon\www\pathravel\vendor\composer\ClassLoader.php on line 412

Call Stack:
    0.0000     130152   1. {main}() C:\laragon\www\pathravel\artisan:0
    0.0520    1934904   2. spl_autoload_call() C:\laragon\www\pathravel\artisan:34
    0.0520    1934960   3. Composer\Autoload\ClassLoader->loadClass() C:\laragon\www\pathravel\artisan:34
    0.0520    1934960   4. Composer\Autoload\includeFile() C:\laragon\www\pathravel\vendor\composer\ClassLoader.php:301

Fatal error: Class 'Symfony\Component\Console\Input\ArgvInput' not found in C:\laragon\www\pathravel\artisan on line 34

Call Stack:
    0.0000     130152   1. {main}() C:\laragon\www\pathravel\artisan:0

What should i do?

**Comment by iBet7o** [comment]
https://github.com/sensiolabs/SensioDistributionBundle/issues/243
