### ISSUE TITLE
directory of models

### ISSUE THREAD

**Issue by kalvish21** [laracasts/Laravel-5-Generators-Extended#92]
I'm putting all my models in App/models. Is there a way I can configure the generator to use that directory?

**Comment by dswtech** [comment]
You can just insert command make:model models/YourModel

**Comment by RanZix** [comment]
Go to vendor/laracasts/generators/src/Commands/MigrationMakeCommand.php, on line 107 change 
'name' => $this->getModelName()
to
'name' => 'models/'.$this->getModelName()

**Comment by mishbah** [comment]
if this package have config file, we can change the model directory

**Comment by tabacitu** [comment]
Closing this, as you can use ```command make:model Models/YourModel``` as @dswtech said.
