### ISSUE TITLE
timestamp migration file names

### ISSUE THREAD

**Issue by bingalls** [laracasts/Laravel-5-Generators-Extended#94]
I'm running Artisan for all my models on the same day. Unfortunately, database/migrations/*.php can be generated in random order, not in increasing order. Thus, if `students` has a foreign key to `teachers`, Artisan can generate
- 2016_02_13_185904_create_students_table.php
- 2016_02_13_185916_create_teachers_table.php
  regardless of whether I run `artisan make:migration:schema create_teachers_table --schema=...` before, or after the 'make' for students table.

Please use timestamps, or similar monotonic numbering scheme.

**Comment by tabacitu** [comment]
Thanks @bingalls for raising the issue. I see that's been fixed in the meantime, looks like we're doing ```base_path().'/database/migrations/'.date('Y_m_d_His').'_'.$name.'.php'``` now.

Cheers!
