### ISSUE TITLE
how can create extra fields on pivot table

### ISSUE THREAD

**Issue by Mohib1992** [laracasts/Laravel-5-Generators-Extended#95]
There is command to create migration for pivot table
php artisan make:migration:pivot $table1 $table2.

Is there any way to do like
php artisan make:migration:pivot $table1 $table2 --schema="field1:string, field2:string"

**Comment by tabacitu** [comment]
I believe PR https://github.com/laracasts/Laravel-5-Generators-Extended/pull/114 would add that functionality. We're considering adding it in v2 https://github.com/laracasts/Laravel-5-Generators-Extended/pull/165 soon - let us know what you think about this PR in #114 if you still want the feature.

It's finally time to make this package better for us all to benefit. Let's do this!
Cheers!
