### ISSUE TITLE
Error when create a large migration table

### ISSUE THREAD

**Issue by kykylkan** [laracasts/Laravel-5-Generators-Extended#99]
Error when table isset > 8 columns or maybe schema string is too large( :
assertion "newSize >= 0" failed: file "main.cc", line 227, function: std::string convertPosixPathToWin(const string&)
Aborted (core dumped)

**Comment by tabacitu** [comment]
Sorry @kykylkan but I haven't been able to replicate the issue, so I'm going to close this. Please reply here if it's still a thing, and we should reopen.

Cheers!
